#!/usr/bin/env python
import sys, os

try:
    from waflib.extras import symwaf2ic
    recurse = lambda *args, **kwargs: None
except ImportError:
    from symwaf2ic import recurse_depends
    recurse = lambda ctx: recurse_depends(depends, ctx)

def depends(ctx):
    ctx('calibtic', 'backends/xml')
    ctx('calibtic', 'backends/binary')
    ctx('calibtic', 'backends/text')

def options(opt):
    recurse(opt)

def configure(cfg):
    recurse(cfg)

def build(bld):
    recurse(bld)
