#!/usr/bin/env python
import sys, os
try:
    from waflib.extras import symwaf2ic
    from waflib.extras.gtest import summary
    recurse = lambda *args: None # dummy recurse
except ImportError:
    from gtest import summary
    from symwaf2ic import recurse_depends
    recurse = lambda ctx: recurse_depends(depends, ctx)

def depends(ctx):
    ctx('calibtic')
    ctx('calibtic', 'HMF')

def options(opt):
    recurse(opt)
    opt.load('compiler_cxx')
    opt.load('boost')

def configure(cfg):
    recurse(cfg)
    cfg.load('compiler_cxx')
    cfg.load('boost')

    cfg.check_boost(
            lib='filesystem serialization system',
            uselib_store='BOOST4CALIBTICXML')

def build(bld):
    recurse(bld)

    flags = {
            "lib" : [ 'dl', ],
    }

    bld.shlib(
            target          = 'calibtic_xml',
            source          = bld.path.ant_glob('*.cpp'),
            use             = [
                'BOOST4CALIBTICXML',
                'calibtic',
                'hmf_calibration',
                ],
            includes        = '.',
            install_path    = '${PREFIX}/lib',
            **flags
    )
