#!/usr/bin/env python

def depends(ctx):
    ctx('calibtic')
    ctx('calibtic', 'HMF')

def options(opt):
    opt.load('compiler_cxx')
    opt.load('boost')

def configure(cfg):
    cfg.load('compiler_cxx')
    cfg.load('boost')

    cfg.check_boost(
            lib='filesystem serialization system',
            uselib_store='BOOST4CALIBTICTEXT')

def build(bld):

    bld.shlib(
            target          = 'calibtic_text',
            source          = bld.path.ant_glob('*.cpp'),
            use             = [
                'BOOST4CALIBTICTEXT',
                'calibtic',
                'hmf_calibration',
                ],
            includes        = '.',
            install_path    = '${PREFIX}/lib',
    )
